name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gdal:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        gdal-image: ["osgeo/gdal:ubuntu-small-latest", "osgeo/gdal:ubuntu-small-3.1.3", "geographica/gdal2:2.4.3"]
      fail-fast: false

    container: ${{ matrix.gdal-image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install python3-pip -y
          python3 -m pip install .["test"] --no-binary rasterio

      - name: Run Test
        run: python3 -m pytest --cov morecantile --cov-report term-missing --ignore=venv
        env:
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
