name: Run Tests on different GDAL Versions

on:
  push:
    branches:
      - master

jobs:
  gdal:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        rasterio-version: ["1.1.8", ">=1.2"]
        # Rasterio 1.1.8 wheels come with GDAL 2
        # Rasterio 1.2.3 wheels come with GDAL 3.2
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .["test"] rasterio==${{ matrix.rasterio-version }}

      - name: Run Test
        run: python -m pytest --cov morecantile --cov-report term-missing --ignore=venv
        env:
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
